### ISSUE TITLE
[Bug]: Teensy 2.0 pin mapping is wrong

### ISSUE THREAD

**Issue by p-elsie** [Arduino-IRremote/Arduino-IRremote#1002]
### The type of board you are using.

Teensy board

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

NEC

### Pin(s) used for IR-receive, if not default.

Arduino pin number: none

### Example(s) you have checked while hunting the bug.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] MinimalReceiver
- [ ] ReceiveAndSend
- [X] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] MinimalReceiver
- [ ] ReceiveAndSend
- [X] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [X] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

Use a Teensy 2.0, and modify the loop, such that we're always sending. Use a red LED (or other visible light LED) to determine which PIN we're actually sending on. 

Changed line 199 of PinDefinitionsAndMore.h as follows:

elif defined(TEENSYDUINO)
#define IR_RECEIVE_PIN      2
#define IR_SEND_PIN         13 (line 199)

Try all the PIN numbers and determine which PIN actually gets the signal. 

### What happens?

The Teensy PINs are not mapped correctly. The output is directed to the wrong pin. 

### Additional context.

 /* 
  *  Workaround for defective behaviors on Teensy 2.0:
  *  
  *  When IR_SEND_PIN 3,connect LED to PIN 5
  *  0, 7
  *  1, none work
  *  2, 7
  *  3, 5
  *  4, none work
  *  5, 9
  *  6, 12
  *  7, none work
  *  8, 13
  *  9, 14
  *  10, none work
  *  11, 4
  *  12, 11
  *  13, 10 
  *  Investigation of other Teensy 2.0 PIN mismapping is left to others. 
  *  
  */
  
  I wanted to use PIN 10, because I have the LED soldered to it already, from a previous use case, with much older code. 
  
  To make pin 10 work, I changed line 199 of PinDefinitionsAndMore.h as follows:

elif defined(TEENSYDUINO)
#define IR_RECEIVE_PIN      2
#define IR_SEND_PIN         13 (line 199)

Tested with Arduino 1.8.19, and IRRemote 3.7.1

I've verified with Basics>Blink that, in that case, the pin mapping is correct, and matches the official Teensyduino pinout. This seems to be an issue with the Arduino-IRremote library. 

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
I added mapping for teensy 2.0
Can you please get the latest version from tis repository and test it?

**Comment by p-elsie** [comment]
Pins 0,1,2,3,5,6,8,9,10,11,12,14,15,20,21 are correct. 

Coded Pin | Response Pin
4 | none
7 | 12
13 | none
16 | 18
 17 | 19
18 | none
19 | none

That's much better. Thank you!!!

**Comment by p-elsie** [comment]
I didn't recheck all the pins. But I checked all the ones that weren't right before, and they all look good. 

Coded Pin | Response Pin
3|3
4 | 4
7 | 7
13|13
16|16
17|17
18|18
19| 19

**Comment by p-elsie** [comment]
I think that your changes to digitalWriteFast.h are good. But something was changed in examples/SimpleSender/PinDefinitionsAndMore.h that doesn't work for me. When I use the current version of that, IR_SEND_PIN is always 3, even when I change the value specified n this code:

#elif defined(TEENSYDUINO) // Teensy 2.0 is handled at default for ATmega328 like on Uno, Nano, Leonardo etc.
#define IR_RECEIVE_PIN      2
#define IR_SEND_PIN         3

However, the version PinDefinitionsAndMore.h that precedes this issue report, works fine in that respect.

**Comment by ArminJo** [comment]
> But something was changed in examples/SimpleSender/PinDefinitionsAndMore.h that doesn't work for me. When I use the current version of that, IR_SEND_PIN is always 3, even when I change the value specified in this code:

Yes, this is intended. Teensy 2.0 is covered by the ATmega328 pin mapping now, as noted in the Teensy comment.
But I forget to mention it in the ATmega328 comment. It is now:
`#  else // Default as for ATmega328 like on Uno, Nano, Leonardo, Teensy 2.0 etc.`
