### ISSUE TITLE
[Bug]: MAGIQUEST protocol truncated wand id returned.

### ISSUE THREAD

**Issue by thanneman79** [Arduino-IRremote/Arduino-IRremote#1017]
### The type of board you are using.

Arduino ATmega328* board (UNO, Nano, etc.)

### What IDE are you using?

Other - please specify below

### What IR protocol are you using?

Other - please specify below

### Pin(s) used for IR-receive, if not default.

Arduino pin number: 

### Example(s) you have checked while hunting the bug.

- [X] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] MinimalReceiver
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [X] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] MinimalReceiver
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [X] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

Run SimpleReciever and output command and address fields.

### What happens?

ir_MagiQuest.hpp returns truncated wand id, only returning the last 16 bits of the 32 bit wand id because address field of decodedIRData that it is put into on line 204 is a uint16_t. 

Similarly llword being uint64_t is being truncated being put into decodedIRData.decodedRawData (uint32_t) on line 203. 

Since there is nothing of use coming from the wand but the magnitude (passed already on 205 I would recommend just passing the wand id in the decodedRawData field. It doesn't fit the pattern of the other protocols but is my solution locally for now.

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Could it be a solution for you to have the upper 16 bits of the wand ID in the decodedIRData.extra field?
This has the advantage of not breaking the semantics of the fields.
