### ISSUE TITLE
[Bug]: SendProntoDemo causes bootloop on ESP8266

### ISSUE THREAD

**Issue by drelephant** [Arduino-IRremote/Arduino-IRremote#1068]
### The type of board you are using.

Other - please specify below

### The boards name or FQBN (e.g. esp8266:esp8266:d1_mini:eesz=4M3M,xtal=80) for unspecified board.

esp8266:d1_mini

### The board manager URL used for unspecified board.

??

### What IDE are you using?

Arduino IDE 1.8.5

### What IR protocol are you using?

Pronto

### Pin(s) used for IR-receive, if not default.

Arduino pin number: default (12)

### Example(s) you have checked while hunting the bug.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] MinimalReceiver
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [X] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] MinimalReceiver
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [X] Other - please specify below

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [ ] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

Try to run SendProntoDemo.ino on an esp8266 (Wemos D1 Mini) using Arduino 1.8.5.

I have tried using 80Mhz and 160Mhz.

The other examples seem to work however.

### What happens?

````
START SendProntoDemo.ino from Dec 24 2022
Using library version 3.9.0
Ready to send IR signals at pin 12
Sending from normal memory

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (3):
epc1=0x4000bf64 epc2=0x00000000 epc3=0x00000000 excvaddr=0x40238bad depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffdc0 end: 3fffffc0 offset: 0190
3fffff50:  40201658 3ffe8930 3ffee850 40201664  
3fffff60:  40201658 3ffe8930 3ffee850 402017fc  
3fffff70:  40238bad 0000001a 3ffee850 402018b8  
3fffff80:  3fffdad0 3ffee850 3ffee850 3ffee8b8  
3fffff90:  3fffdad0 3ffee850 3ffee618 402014d9  
3fffffa0:  feefeffe 00000000 3ffee8a4 40201ee4  
3fffffb0:  feefeffe feefeffe 3ffe85d8 40100ca5  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3460, room 16 
tail 4
chksum 0xcc
load 0x3fff20b8, len 40, room 4 
tail 4
chksum 0xc9
csum 0xc9
v000429f0
~ld
````
... repeats over and over

### What were you expecting to happen?

Sending pronto IR from the esp8266.

### Final checklist for the bug report.

- [x] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Thanks for reporting! 🥇
