### ISSUE TITLE
[Bug]: Auto repeat flag set even when keys are differents

### ISSUE THREAD

**Issue by Franck78** [Arduino-IRremote/Arduino-IRremote#1075]
### The type of board you are using.

ESP32 board - first check https://github.com/crankyoldgit/IRremoteESP8266

### The boards name or FQBN (e.g. esp8266:esp8266:d1_mini:eesz=4M3M,xtal=80) for unspecified board.

esp32-S3

### The board manager URL used for unspecified board.

https://

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

NEC

### Pin(s) used for IR-receive, if not default.

Arduino pin number: default

### Example(s) you have checked while hunting the bug.

- [ ] SimpleReceiver
- [X] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [X] Other - please specify below

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [ ] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

Hello,

In my project, I manage the receiver & the transmitter.
This is tested with RC6 only and on an ESP32-S3 receiver and the Atmega88 as emitter.

EMITTER

```
   // sending 21 as two consecutive digits
    IrSender.sendRC6( IRaddress(0,1),    2  , 0);
    delay(60);                                                                        <====== varying (0, 60, 150, 500)
    IrSender.sendRC6( IRaddress(0,1),    1   , 0);

```
RECEIVER SIDE
is            IrReceiver.printIRResultShort(&Serial);   (in the loop).

```
Protocol=UNKNOWN 38 bits (incl. gap and start) received
Protocol=UNKNOWN 38 bits (incl. gap and start) received

Protocol=RC6 Address=0x1 Command=0x2 Raw-Data=0x102 20 bits MSB first
Protocol=RC6 Address=0x1 Command=0x1 Toggle=1 Repeat gap=60000us Raw-Data=0x10101 20 bits MSB first

Protocol=RC6 Address=0x1 Command=0x2 Raw-Data=0x102 20 bits MSB first
Protocol=RC6 Address=0x1 Command=0x1 Toggle=1 Repeat gap=100050us Raw-Data=0x10101 20 bits MSB first

Protocol=RC6 Address=0x1 Command=0x2 Raw-Data=0x102 20 bits MSB first
Protocol=RC6 Address=0x1 Command=0x1 Toggle=1 Raw-Data=0x10101 20 bits MSB first
```

First if the delay is zero, there is a collision , unexpected but this not the problem.

A minimal delay of 50 must be inserted so that receiver is ok.

Problem, the receiver sets the repeat flag and this is very not expected because keys are not the same  ('2' '1').

After an unnecessary long delay, the flag is not used. ~ 500 

Note also "Toggle=1" appearing. I have not search the meaning of it.

### What happens?

Cannot have a reliable receiving function.

I have red the code and I don't find anywhere a comparison between previous code and last ne received. You check the time only. If they are different, it is not a repeat (or auto_repeat)

Also not found description for difference between auto or not auto_repeat. I was imagining one case  is a furious usage of any keys without delays, the other case a real long press of the same key.

```
/*
 * Definitions for member IRData.flags
 */
#define IRDATA_FLAGS_EMPTY              0x00
#define IRDATA_FLAGS_IS_REPEAT          0x01
#define IRDATA_FLAGS_IS_AUTO_REPEAT     0x02
```

### The serial output which indicates the error happened.

```shell
another view on the receiver. Instead of "21" I compute "2" because the "1" is eliminated as a repeat

FLAGS = 80   MSB_FIRST
FLAGS = 89   FLAGS_IS_REPEAT+TOGGLE+MSB_FIRST
RIR:2
```
```


### What were you expecting to happen?

x

### Additional context.

x

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Thanks for reporting.
I documented it in the sources now.
IRDATA_FLAGS_IS_AUTO_REPEAT means: The current repeat frame is a repeat, that is always sent after a regular frame and cannot be avoided. Only specified for protocols DENON, and LEGO.
IRDATA_FLAGS_IS_REPEAT means: The gap between the preceding frame is as smaller than the maximum gap expected for a repeat. !!!We do not check for changed command or address!!!

**Comment by Franck78** [comment]
> We do not check for changed command or address!!!

ah, maybe at link level most of this info (IRDATA_FLAGS)  is useful. But at application level, there is no use for this.

This detection can be done at app level but really each decoder is the most suited place to do it accurately .

Can you think of it please ?  Use bit 0x20 for that.

**Comment by ArminJo** [comment]
In many protocols, it is not possible to distinguish between two fast presses of the same button and one long press.
And  it is almost not possible to press 2 different buttons on the remote within around 100 ms.
And the check consumes around 85 bytes of program memory.

**Comment by Franck78** [comment]
Yeah, but as you know, you also wrote the Sender. And the sender has no problem sending codes at 'normal' throughput. Inserting a fake 'human' delay makes zero sense.

Detecting this reliably  is mandatory. Without that, it simply means that all Senders can be removed from the repo except for one that has to be to made resistant to this usage.

The  advantage of having them all (for sending) is choosing the one with less resources usage on one side, or best error detection, or shorter frames or compatible with the boxe of remote you mistakenly ordered ;)

At least do it between ifdefs for one protocol (say RC6). It will be 500% better done than any other contrib.

**Comment by Franck78** [comment]
ArminJo added theses lines in commit https://github.com/Arduino-IRremote/Arduino-IRremote/commit/ad0425f5544636b673cb070bbafb4a8762a9c4f2

and every decoded protocol is calling it. 

```
#if defined(ENABLE_FULL_REPEAT_CHECK)
            && decodedIRData.address == lastDecodedAddress && decodedIRData.command == lastDecodedCommand /* requires around 85 bytes program space */
#endif

```
IRDATA_FLAGS_IS_REPEAT can be trusted.
