### ISSUE TITLE
[Bug]: compiler warning

### ISSUE THREAD

**Issue by Franck78** [Arduino-IRremote/Arduino-IRremote#1076]
### The type of board you are using.

ESP32 board - first check https://github.com/crankyoldgit/IRremoteESP8266

### The board manager URL used for unspecified board.

https://

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

NEC

### Pin(s) used for IR-receive, if not default.

Arduino pin number: default

### Example(s) you have checked while hunting the bug.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [X] Other - please specify below

### The library version you are working with.

- [ ] I use the [latest Arduino library version](../releases) and verified this!
- [X] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

build an app

A compiler warning pointing a potential problem with size (16 / 32 bits) in Samsung

### What happens?

```
In file include Arduino/libraries/IRremote/src/IRremote.hpp:309,
                 from xxx
IRremote/src/ir_Samsung.hpp: In member function 'void IRsend::sendSamsung48(uint16_t, uint16_t, int_fast8_t)':
IRremote/src/ir_Samsung.hpp:200:18: warning: comparison is always true due to limited range of data type [-Wtype-limits]
     if (aCommand < 0x10000) {
         ~~~~~~~~~^~~~~~~~~
```

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Thamks for reporting 👍 .
