### ISSUE TITLE
[Bug]: error when using hardware serial on other library without using USB-/serial-debugging

### ISSUE THREAD

**Issue by GralfR** [Arduino-IRremote/Arduino-IRremote#1094]
### The type of board you are using.

Arduino ATmega328* board (UNO, Nano, etc.)

### The board manager URL used for unspecified board.

https://

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

Unknown

### Pin(s) used for IR-receive, if not default.

Arduino pin number: default

### Example(s) you have checked while hunting the bug.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [X] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [X] Other - please specify below

### The library version you are working with.

- [ ] I use the [latest Arduino library version](../releases) and verified this!
- [X] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

include IRremote and DMXserial into one script like:

```
#include "PinDefinitionsAndMore.h"
#include <IRremote.hpp>
#include <DMXSerial.h>

void setup() {

}

void loop() {

}
```

Get DMXserial from [here](https://github.com/mathertel/DMXSerial).

### What happens?

compiler error: multiple definitions of "__vector_18" and "__vector_19"
I think this is because DMXserial uses hardwareserial for transmit/receive and IRremote uses serial, too.

I know, the Arduino nano only has one serial. That would be enough, because I do not need any USB-serial monitor or debugging to serial with serial.print.

I didn't find any options to disable serial in IRremote in general. That would be fine.
In my current project I just need IRsendRAW with constant arrays prerecorded with another script. I think/hope this works without ousing any hardware serial.

### The serial output which indicates the error happened.

```shell
-nothing- not using serial...
```

### What were you expecting to happen?

Working code, because I'm not using serial for USB-debugging/monitoring.

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Thank you very much for reporting! 🥇 I fixed it.
