### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AnthonyAC23** [Arduino-IRremote/Arduino-IRremote#1157]
### The type of board you are using.

ESP32 board - first check https://github.com/crankyoldgit/IRremoteESP8266

### The boards name or FQBN (e.g. esp8266:esp8266:d1_mini:eesz=4M3M,xtal=80) for unspecified board.

Wemos Lolin32 lite (ESP32)

### The board manager URL used for unspecified board.

https://

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

Unknown

### Pin(s) used for IR-receive, if not default.

Arduino pin number:  32

### Example(s) you have checked while hunting the bug.

- [X] SimpleReceiver
- [X] ReceiveDemo
- [X] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [X] SimpleReceiver
- [X] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [ ] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

Use a WEMOS LOLIN32 LITE (ESP32) board
use pin 32 as data input
make use of a demo and verify
shows a library error in
IRremote.hpp:274:0, IRremote.h:10
IRTimer.hpp:1911:2: error: #endif without #if
error: missing binary operator before token "("
#if ESP_ARDUINO_VERSION < ESP_ARDUINO_VERSION_VAL(2, 0, 2)
^
#endif // _IR_TIMER_HPP
due to ESP32 versions
It is worth mentioning that before updating from the Arduino IDE the library did not show this error

### What happens?

Statement error when using ESP32 based boards

### The serial output which indicates the error happened.

```shell
IRremote.hpp:274:0, IRremote.h:10
IRTimer.hpp:1hpp:1372:50 error: missing binary operator before token "("
#if ESP_ARDUINO_VERSION < ESP_ARDUINO_VERSION_VAL(2, 0, 2)
^
#endif

//comment part line 1373
#if ESP_ARDUINO_VERSION < ESP_ARDUINO_VERSION_VAL(2, 0, 2) //<====== mark error in this part saying that "a function call to a constant expression is not allowed"
void timerDisableReceiveInterrupt() {
    if (s50usTimer != NULL) {
        timerEnd(s50usTimer);
        timerDetachInterrupt(s50usTimer);
    }
}
#else
void timerDisableReceiveInterrupt() {
    if (s50usTimer != NULL) {
        timerAlarmDisable (s50usTimer);
    }
}
#endif
```

### What were you expecting to happen?

that it will work as it did before the update

### Additional context.

There is only one problem with those conditional statements, it is worth mentioning that for the moment in order not to stop using the most recent version I have commented the lines concerning said condition and it has worked for me, but it would be great if they would review and fix it. thank you

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Already fixed a few moth ago!
