### ISSUE TITLE
[Bug]: Arduino UNO R4 transmit not working as expected

### ISSUE THREAD

**Issue by vickash** [Arduino-IRremote/Arduino-IRremote#1175]
### The type of board you are using.

Other - please specify below

### The boards name or FQBN (e.g. esp8266:esp8266:d1_mini:eesz=4M3M,xtal=80) for unspecified board.

arduino:renesas_uno:unor4wifi

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

Samsung

### Pin(s) used for IR-receive, if not default.

Arduino pin number: default

### Example(s) you have checked while hunting the bug.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [X] SimpleSender
- [X] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [X] SimpleSender
- [X] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [ ] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

I tried `SimpleSender.ino` on the R4, with a second Mega 2560 hooked up as a receiver, running `ReceiveDump.ino`.

### What happens?

`SimpleSender.ino` does:
```
IrSender.sendSamsung48(0xB24D, 0xCF9, 2);
```
but the Mega receives wrong data (see serial output). Data is not consistent between different tries either.

### The serial output which indicates the error happened.

```shell
3 different instances sent from the UNO R4:

Protocol=UNKNOWN Hash=0x313F98CF 45 bits (incl. gap and start) received
Received noise or an unknown (or not yet enabled) protocol

Raw result in microseconds - with leading gap
rawData[90]: 
 -1035300
 +4500,-4400
 + 550,-1700 + 600,- 550 + 600,-1650 + 550,- 400
 + 550,- 550 + 600,- 550 +1300,- 400 + 550,- 600
 + 550,-1700 + 550,- 550 + 400,- 600 + 550,- 900
 + 550,- 400 + 600,- 550 + 600,-1650 + 600,-1650
 + 350,- 500 + 450,- 550 + 450,-1650 + 350,-1650
 + 650,- 650 + 550,- 450 + 550,-1700 +1250,- 450
 + 550,-1700 +1300,- 400 + 600,- 550 + 600,- 550
 +1250,- 400 + 600,- 550 + 550,-1700 + 550,-1700
 + 350,- 550 + 350,- 600 + 450,- 550 + 600,- 550
 + 500,- 750 + 550,-1700 +1250,- 500 + 500,-1750
 + 500,- 100 + 600,- 500 + 500,-1750 + 500
Sum: 74700


Protocol=UNKNOWN Hash=0xBED87630 46 bits (incl. gap and start) received
Received noise or an unknown (or not yet enabled) protocol

Raw result in microseconds - with leading gap
rawData[92]: 
 -1040100
 + 500,-1700
 + 300,- 550 + 400,-1700 + 600,- 700 + 600,- 400
 + 550,- 550 + 600,-1650 + 600,- 550 + 550,- 600
 + 650,- 600 + 550,- 600 + 550,- 600 +1250,- 450
 + 550,- 400 + 550,-1700 + 500,- 150 + 600,- 650
 + 450,- 650 + 500,-1750 + 350,-1750 + 300,-1700
 + 600,- 700 + 500,- 500 + 500,- 650 + 450,-1800
 + 450,-1800 + 300,- 550 + 350,- 650 + 350,- 650
 + 550,- 550 + 500,- 650 + 600,- 550 + 500,- 650
 + 450,- 350 + 500,- 500 + 500,- 500 + 500,- 650
 + 500,- 600 +1200,- 500 + 500,-1750 + 500,- 150
 + 600,- 450 + 550,-1700 +1250,- 500 + 550,-1700
 + 550
Sum: 63750

Protocol=UNKNOWN Hash=0xA45A60F9 46 bits (incl. gap and start) received
Received noise or an unknown (or not yet enabled) protocol

Raw result in microseconds - with leading gap
rawData[92]: 
 -1039900
 + 600,- 900
 + 550,- 600 + 550,-1700 + 550,-1700 + 350,- 500
 + 400,- 600 + 450,-1650 + 350,- 550 + 350,- 600
 + 450,-1650 + 400,- 500 + 400,- 600 + 600,- 800
 + 550,- 450 + 550,- 600 + 550,-1700 + 550,-1700
 + 300,- 550 + 400,- 600 + 400,-1700 + 250,-1700
 + 500,- 800 + 500,- 500 + 500,-1750 + 500,- 150
 + 550,- 500 + 500,-1750 + 500,- 150 + 600,- 500
 + 450,- 650 + 650,- 550 +1200,- 450 + 550,- 600
 + 500,-1750 + 600,-1650 + 250,- 600 + 350,- 650
 + 300,- 700 + 450,- 700 + 500,- 750 + 600,-1650
 +1200,- 500 + 500,-1750 +1300,- 400 + 600,-1650
 + 550
Sum: 66700
```

### What were you expecting to happen?

EXPECTED OUTPUT (confirmed by sending from ESP32):
```
Protocol=Samsung48 Address=0xB24D Command=0xCF9 Raw-Data=0xF30C 48 bits LSB first

Send with: IrSender.sendSamsung48(0xB24D, 0xCF9, <numberOfRepeats>);

Raw result in microseconds - with leading gap
rawData[100]: 
 -994550
 +4450,-4450
 + 550,-1700 + 550,- 550 + 550,-1650 + 600,-1650
 + 550,- 600 + 500,- 600 + 550,-1650 + 550,- 600
 + 500,- 600 + 550,-1650 + 600,- 550 + 550,- 550
 + 550,-1700 + 550,-1650 + 550,- 600 + 550,-1650
 + 550,-1700 + 550,- 550 + 550,- 550 + 600,-1650
 + 550,-1700 + 550,-1650 + 550,-1700 + 550,-1650
 + 550,- 600 + 500,-1700 + 550,-1700 + 550,- 550
 + 550,- 600 + 500,- 600 + 550,- 550 + 550,- 550
 + 600,- 550 + 550,- 550 + 550,-1700 + 550,-1650
 + 550,- 600 + 550,- 550 + 550,- 550 + 600,- 550
 + 550,-1700 + 500,-1700 + 550,- 600 + 500,- 600
 + 500,-1700 + 550,-1700 + 500,-1700 + 550,-1700
 + 500
Sum: 89700
```

### Additional context.

I also tried `SendDemo.ino`, and a raw array of my own (Midea protocol). Data was corrupted just like the `SimpleSender.ino` example.

Receiving on the R4 appears to work fine btw. When I reversed the setup and sent from the Mega to the R4, all data was correct.

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
A known bug.
I updated the Readme.
