### ISSUE TITLE
[Bug]: I can't send some Samsung or NEC IR code

### ISSUE THREAD

**Issue by terosque** [Arduino-IRremote/Arduino-IRremote#1182]
### The type of board you are using.

Arduino ATmega328* board (Uno, Nano, etc.)

### The board manager URL used for unspecified board.

https://

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

Samsung

### Pin(s) used for IR-receive, if not default.

Arduino pin number: default (3)

### Example(s) you have checked while hunting the bug.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [X] TinySender
- [X] ReceiveAndSend
- [ ] SimpleSender
- [X] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [X] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [X] TinySender
- [X] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [X] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

Protocol=Samsung Address=0x707 Command=0x2 Raw-Data=0xFD020707 32 bits LSB first
Send with: IrSender.sendSamsung(0x707, 0x2, <numberOfRepeats>);

Button pressed, now sending raw 179 marks or spaces
Button released -> start receiving
Stop receiving
Button pressed, now sending raw 179 marks or spaces
Button released -> start receiving
Stop receiving

### What happens?

i don't really know what happen but just it won't want to communicate with my TV like i see the light of the LED with the camera but nothing is happening.

### The serial output which indicates the error happened.

```shell
+1000,-4600 + 950,-4600 +1000,-4650 + 900,-4600
 +1000,-4600 +1000,-5050 + 250,-4850 + 950,-4750
 + 850
Sum: 494300
Stop receiving
Button pressed, now sending raw 179 marks or spaces
Button released -> start receiving
Stop receiving
Button pressed, now sending raw 179 marks or spaces
Button released -> start receiving
Stop receiving
Button pressed, now sending raw 179 marks or spaces
Button released -> start receiving
```

### What were you expecting to happen?

Send the IRcode i recieved and like clone a telecommand

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Dont spam this repo!
It is your issue not one of the library!
