### ISSUE TITLE
[Bug]: Can't end() and begin() on Arduino Uno R4 Wifi

### ISSUE THREAD

**Issue by SJrX** [Arduino-IRremote/Arduino-IRremote#1215]
### The type of board you are using.

Other - please specify below

### The boards name or FQBN (e.g. esp8266:esp8266:d1_mini:eesz=4M3M,xtal=80) for unspecified board.

arduino:renesas_uno:unor4wifi

### The board manager URL used for unspecified board.

https://downloads.arduino.cc/packages/package_index.json

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

Unknown

### Pin(s) used for IR-receive, if not default.

6

### Example(s) you have checked while hunting the bug.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [X] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [X] Other - please specify below

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [X] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

1. Try ending and beginning with IrReceiver many times.

```
#include "IRremote.h"
#define IR_PIN 6
void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);   
  Serial.println("*** Reboot ***"); // initialize serial communication
  IrReceiver.begin(IR_PIN, true);

}

int loopCount = 0;
void loop() {
  // put your main code here, to run repeatedly:

  if (!IrReceiver.isIdle()) {
    return;
  }

  loopCount++;


  if (loopCount % 10 == 3 ) { 
      Serial.println("Disabling IR");
      IrReceiver.end();
      Serial.println("Done");
  }


  if (loopCount % 10 == 5 ) { 
      Serial.println("Enabling IR");
      IrReceiver.begin(IR_PIN, true);
      Serial.println("Done");
  }
  delay(100);
}
```

### What happens?

This code hangs almost immediately, sometimes it makes it past the first Enable, but over four samples it didn't go anywhere.

### The serial output which indicates the error happened.

```shell
16:37:04.678 -> Disabling IR
16:37:04.678 -> Done
16:37:04.903 -> Enabling IR
16:37:08.636 -> *** Reboot *** (Pressing Reboot button)
16:37:08.830 -> Disabling IR
16:37:08.830 -> Done
16:37:09.023 -> Enabling IR
16:37:09.023 -> Done
16:37:09.828 -> Disabling IR
16:37:09.828 -> Done
16:37:10.053 -> Enabling IR
16:37:11.827 -> *** Reboot *** (Pressing Reboot Button)
16:37:12.018 -> Disabling IR
16:37:12.018 -> Done
16:37:12.211 -> Enabling IR
16:37:12.211 -> Done
16:37:13.015 -> Disabling IR
16:37:13.015 -> Done
16:37:13.239 -> Enabling IR
16:37:21.336 -> *** Reboot *** (Pressing Reboot Button)
16:37:21.527 -> Disabling IR
16:37:21.527 -> Done
16:37:21.753 -> Enabling IR
16:37:21.753 -> Done
16:37:22.559 -> Disabling IR
16:37:22.559 -> Done
16:37:22.752 -> Enabling IR
16:37:25.726 -> *** Reboot *** (Pressing Reboot Button)
16:37:25.919 -> Disabling IR
16:37:25.919 -> Done
16:37:26.112 -> Enabling IR
16:37:26.112 -> Done
16:37:26.917 -> Disabling IR
16:37:26.917 -> Done
16:37:27.141 -> Enabling IR
```

### What were you expecting to happen?

This could should loop indefinitely. 

### Additional context.

1. I was able to reproduce this on 2x Uno R4 Wifi Boards, someone on the internet also reproduced this using an IR Receiver TSOP381, mine is maybe a VS1838B, and I've tried two of them. I also added a 5K resististor.

2. I did look at the examples but none of them actually call end().

3. Running this code on an Mega2560 R3, or a R1 Giga Wifi had no issues.

4. The reason I went down this path is because of another issue I'm having where essentially the IR receiver stops working entirely. I had tried to end() and begin()  as a hack, but then ran into this issue. I suspect it's not the most important problem. 

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Thanks for reporting, but R4 is not well supported because of lack of a R4 board.
