### ISSUE TITLE
Multiple IR Receivers not working for more than 4 Instances.

### ISSUE THREAD

**Issue by Hixaa** [Arduino-IRremote/Arduino-IRremote#1233]
I'm using https://github.com/Neco777/Arduino-IRremote Library for Multiple IR Reception.

### The type of board you are using.

Arduino ATmega328* board (Uno, Nano, etc.)

### The board manager URL used for unspecified board.

https://

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

RC5, RC6

### Pin(s) used for IR-receive, if not default.

6,10,11,A1,A3,A5

### Example(s) you have checked while hunting the bug.

- [X] SimpleReceiver
- [X] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [X] Other - please specify below
Example Name: IRrecvMulti.ino

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [X] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

1. I'm generating 6 instances of IRrecv in array.
2. The code works for the first 4 instances but when I enable the instances for more than 4, the code is not working. 
3. Slowing down the reading process of IR

### What happens?

I am currently encountering an issue with using multiple IR receivers with a single Arduino UNO controller. Specifically, I am working with six TSOP4838 IR receivers and have been utilizing the following library for multiple reception:

[Arduino-IRremote Library](https://github.com/Neco777/Arduino-IRremote)

While the library functions perfectly for up to four instances, I have been unable to get it to work for more than four receivers. Reading speed is slowing down. This challenge has stalled my development, and I would greatly appreciate your assistance in resolving this issue.

I have attached the code I am using for your reference.

### The serial output which indicates the error happened.

```shell
See the data reception interval time. Its quite huge when we are using all 6 instances of IRrecv
13:04:55.336 -> Rcv_1:A93
13:04:58.949 -> Rcv_2:A92
13:05:02.843 -> Rcv_3:A95
13:05:06.726 -> Rcv_4:A95
13:05:10.187 -> Rcv_0:A90
13:05:13.828 -> Rcv_1:A92
13:05:17.438 -> Rcv_2:A92
13:05:21.345 -> Rcv_3:A95
13:05:25.182 -> Rcv_4:A95
13:05:28.847 -> Rcv_5:A94
13:05:32.204 -> Rcv_0:A90
13:05:35.852 -> Rcv_1:A92
```

### What were you expecting to happen?

The code worked well for 4 Instances of IRrecv. See the output time interval the recption is happening in milliseconds. 
I'm expecting it to be happen for 6 instances also.
13:02:11.351 -> Rcv_2:A93
13:02:11.387 -> Rcv_3:A94
13:02:11.419 -> Rcv_0:A90
13:02:11.458 -> Rcv_1:A90
13:02:11.492 -> Rcv_3:A92
13:02:11.525 -> Rcv_1:A93
13:02:11.557 -> Rcv_2:A93
13:02:11.594 -> Rcv_3:A94
13:02:11.625 -> Rcv_0:A90
13:02:11.658 -> Rcv_1:A90
13:02:11.693 -> Rcv_3:A92
13:02:11.729 -> Rcv_1:A93
13:02:11.761 -> Rcv_2:A93
13:02:11.798 -> Rcv_3:A94
13:02:11.830 -> Rcv_1:A90

### Additional context.

Code for reference:

//IR_Rx_Def.h
#include "IRremote.h"
#include "CppList.h"
#define INP_1 6
#define INP_2 10
#define INP_3 11
#define INP_4 A1
#define INP_5 A3
#define INP_6 A5
#define FB_INP_1 9
#define FB_INP_2 13
#define FB_INP_3 12
#define FB_INP_4 A0
#define FB_INP_5 A2
#define FB_INP_6 A4
#define RELAY 8

//Expected Commands on Input Pins
#define IR_CMD1 0xa90
#define IR_CMD2 0xa91
#define IR_CMD3 0xa92
#define IR_CMD4 0xa93
#define IR_CMD5 0xa94
#define IR_CMD6 0xa95

//MainCode.ino
#include "IR_Rx_Def.h"
bool _initialized = false;
int rcv_count;
IRrecv **all_rcv;

void setup() {
  if (_initialized) return;
  Serial.begin(9600);
  rcv_count = 4; //Not working when set to 6
  all_rcv = (IRrecv **)malloc(rcv_count*sizeof(int));
  all_rcv[0] = new IRrecv(INP_1);
  all_rcv[1] = new IRrecv(INP_2);
  all_rcv[2] = new IRrecv(INP_3);
  all_rcv[3] = new IRrecv(INP_4);
  // all_rcv[4] = new IRrecv(INP_5); 
  // all_rcv[5] = new IRrecv(INP_6);

  for(int i=0; i<rcv_count; i++)
  {
    all_rcv[i]->enableIRIn();
  }
  
  _initialized = true;
}

void loop() 
{
  for(int i=0; i<rcv_count; i++)
  {
    decode_results results;
    
    if(all_rcv[i]->decode(&results)) 
    {
        Serial.print("Rcv_");
        Serial.print(i);
        Serial.print(":");
        Serial.println(results.value,HEX);
        all_rcv[i]->resume();
    }
  }
}

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Please RTFM carefully
