### ISSUE TITLE
[Bug]: SimpleReceiver sample sketch crashes Arduino nano Connect RP2040

### ISSUE THREAD

**Issue by Philip8704** [Arduino-IRremote/Arduino-IRremote#1238]
### The type of board you are using.

Other - please specify below

### The boards name or FQBN (e.g. esp8266:esp8266:d1_mini:eesz=4M3M,xtal=80) for unspecified board.

Arduino Nano Connect RP2040

### The board manager URL used for unspecified board.

https://docs.arduino.cc/software/ide-v1/tutorials/getting-started/cores/arduino-mbed_nano/

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

JVC, NEC

### Pin(s) used for IR-receive, if not default.

Arduino pin number: default (D3)

### Example(s) you have checked while hunting the bug.

- [X] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [X] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [X] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [ ] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

1. Upload Sample sketch SimpleReceiver
2. Upload fails, loses Serial Port
3. Board crashes and red LED starts blinking SOS - Need to enter Bootloader to recover

### What happens?

As soon as the sketch starts uploading, about 15s in, the LED starts blinking red and the board needs to enter recovery mode by pressing the button twice to recover from the crashes. Serial not recognized anymore until recovered using blink sketch. 

### The serial output which indicates the error happened.

```shell
None
```

### What were you expecting to happen?

Upload to complete and board not to crash

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Thanks for reporting 👍 
It is fixed now in the repo.
Please test and give feedback.
