### ISSUE TITLE
[Bug]: mispelled extern function name prevents being called on callback in TinyReceiver

### ISSUE THREAD

**Issue by air42** [Arduino-IRremote/Arduino-IRremote#1279]
### The type of board you are using.

ATtiny85 board (ATTinyCore by Spence Conde)

### The board manager URL used for unspecified board.

https://

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

NEC

### Pin(s) used for IR-receive, if not default.

Arduino pin number: default

### Example(s) you have checked while hunting the bug.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [X] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [X] TinyReceiver
- [ ] TinySender
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [X] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

use TinyReceiver example with callback enabled:
#define USE_CALLBACK_FOR_TINY_RECEIVER

### What happens?

callback handleReceivedTinyIRData() is not being called

### What were you expecting to happen?

handleReceivedTinyIRData() should have been called

### Additional context.

[TinyIRReceiver.hpp](https://github.com/Arduino-IRremote/Arduino-IRremote/tree/master/src/TinyIRReceiver.hpp)
line 154 is:
extern void handleTinyReceivedIRData();

I think it is mispelled, and should be:
extern void handleReceivedTinyIRData();

Did not specify a protocol, so I guess it is NEC by default.
I guess the bug was introduced with changes in v4.2.1
This example and my stuff worked with a previous version (did not note before lib update)

Thank you for this great library!
And happy holidays :)

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Thank you very much for reporting 🥇 .
