### ISSUE TITLE
Library configuration

### ISSUE THREAD

**Issue by DrDiettrich** [Arduino-IRremote/Arduino-IRremote#302]
The selection of protocols is based on #defines, which require to edit the library for customization. This requires (at least on Windows) a copy of the library, and once the library is configured for one project, it becomes unusable in other projects which require other decoders.

Several workarounds are possible, see my fork on [https://github.com/DrDiettrich/Arduino-IRremote]. When only the required decodeXXX methods are mentioned in user code, the linker omits all other (unused) methods. The related #ifdefs may speed up compilation, but I didn't notice such an effect, so they may be removed from the code.

**Comment by z3t0** [comment]
This has been an issue for quite a long time, I will take a look at your fork and see if I can try and implement something similar.
