### ISSUE TITLE
Send function with protocol parameter

### ISSUE THREAD

**Issue by Phintly** [Arduino-IRremote/Arduino-IRremote#734]
I store values along with protocols that I want to play. To do this, I have to create a switch case for every possible protocol. It would be much more convenient if there was a function that accepts a protocol int as a parameter.

**Comment by ArminJo** [comment]
And what would this function do? I implements a switch!
So if you have one already implemented, you can show your code, maybe we can include it in the common sources.

**Comment by Phintly** [comment]
I didn't know how the library was structured internally. I thought it would be easier to do internally. My code is far too messy to be included in the common sources though. I'll close the issue then.
