### ISSUE TITLE
Homepage is not found. Get 404 error.

### ISSUE THREAD

**Issue by hachi** [Arduino-IRremote/Arduino-IRremote#735]
When I click the link to the homepage on the README.md, or the project description I'm taken to https://z3t0.github.io/Arduino-IRremote/ which shows:

![image](https://user-images.githubusercontent.com/8600/102419670-1f330580-3fb5-11eb-9f22-750f9c25be07.png)

**Comment by ArminJo** [comment]
Thanks for the notification
