### ISSUE TITLE
may  cause an endless loop

### ISSUE THREAD

**Issue by jhao-x** [Arduino-IRremote/Arduino-IRremote#736]
https://github.com/Arduino-IRremote/Arduino-IRremote/blob/563ec5bccee8b1330370015685fe4bcdddf32ad4/src/irReceive.cpp#L235
if irparams.rawlen not reset to 0, in ISR it will set the status IR_REC_STATE_STOP, and alway decode the old  ir data

**Comment by ArminJo** [comment]
Did you test it?

**Comment by jhao-x** [comment]
> Did you test it?

yes, i only press a key of panasonic remote, uart print the data all the time, never stop

**Comment by ArminJo** [comment]
Thanks. Can you please send the code for me to reproduce it?

**Comment by jhao-x** [comment]
void IRrecv::resume() {
    irparams.rawlen = 0;
    irparams.rcvstate = IR_REC_STATE_IDLE;
}

**Comment by ArminJo** [comment]
And with this code, the error can be reproduced?

**Comment by jhao-x** [comment]
> And with this code, the error can be reproduced?

i test it the same error not happen again

**Comment by ArminJo** [comment]
So you can close the issue?
