### ISSUE TITLE
Need to clear 16 bit timer before IR send?

### ISSUE THREAD

**Issue by Jim-2249** [Arduino-IRremote/Arduino-IRremote#744]
I am using a Sparkfun Pro Micro with a ATmega32U4 to control an LG TV. For the Pro Micro, IRremote uses the 16 bit CTC 3 for receiving and sending IR data. To send commands to my LG TV, I use 
  void IRsend::sendLG(unsigned long data, int nbits);
I experienced erratic operation of my LG TV when sending IR commands with this code. Looking at the transmitted data with a scope, I noticed that the header mark which is specified:
#define LG_HEADER_MARK  8400
was usually close to 8400uS, but the mark was often about 4200uS. The rest of the timing seemed correct. I thought maybe the problem was due to the timer's count at the time sendLG was called, so I added TCNT3 = 0;  which clears the timer's counter in the function timerConfigForSend();  I added it to the last line of the function. This seems to have resolved the problem. I have futzed around with the library code quite a bit, so I am not absolutely sure this is the way to fix it.
```
static void timerConfigForSend(uint16_t aFrequencyKHz) {
    const uint32_t pwmval = SYSCLOCK / 2000 / (aFrequencyKHz);
    TCCR3A = _BV(WGM31);
    TCCR3B = _BV(WGM33) | _BV(CS30);
    ICR3 = pwmval;
    OCR3A = pwmval * IR_SEND_DUTY_CYCLE / 100;
    TCNT3 = 0;  // ***added*** clear counter
}
```
I noticed that TCNT3 is set to zero in several timerConfigForReceive(); functions. Should all timerConfigForSend() functions zero their counters?

Thanks -Jim

**Comment by ArminJo** [comment]
Hi Jim, thank you very much for your attention 👍 
You are absolutely right, the TCNT3 = 0; was missing.
I added setting to zero for all 16 bit timers where it is essential, for 8 bit timers it is nice but does not change much.
