### ISSUE TITLE
Update the repo URL

### ISSUE THREAD

**Issue by Neilblaze** [Arduino-IRremote/Arduino-IRremote#752]
Currently, the repo link redirects to :arrow_right: `z3t0.github.io/arduino-irremote`, which returns 404. The link should be updated to :arrow_right: `https://arduino-irremote.github.io/Arduino-IRremote`

**checklist:**
- [x] I have **read** the README.md file thoroughly
- [x] I have searched existing issues to see if there is anything I have missed.
- [x] The title of the issue is helpful and relevant

**Comment by ArminJo** [comment]
There are a lot of links in this repo. Can you specify?

**Comment by Neilblaze** [comment]
@ArminJo this one :point_down: 
![rex](https://user-images.githubusercontent.com/48355572/104437528-e5a1ea00-55b4-11eb-84eb-fb0519b49f73.JPG)

**Comment by ArminJo** [comment]
Thanks 👍 
I never used it and there is no website for this repo any more, so I deleted it.
