### ISSUE TITLE
Arduino Nano 12v LED Strip Pin 11 & 3 PWM issue

### ISSUE THREAD

**Issue by alfuraiji** [Arduino-IRremote/Arduino-IRremote#753]
Hi, I'm working on a two 12v RGB Strips controller with an IR sensor for Remote Controlling.
I'm using Arduino Nano and this is the diagram  :
[https://imgur.com/a/YaSmUPp](https://imgur.com/a/YaSmUPp)

I'm facing an issue with controlling the Blue/GREEN LEDs on Pin 11 & 3  the Arduino will not work and the serial monitor only receiving the IR signal and decode it once. my circuit is fine the code is fine and works with the rest LEDs except the ones on pin 11 and 3  if I removed the IR sensor stuff ( code ) the whole circuit works fine with analogWrite for all six LEDs ... after googling somebody mentioned that it's a timer configuration issue with the IRremote library, unfortunately, I didn't find a clear answer to how to fix this especially most of the answers only advising me to change the pin but I can't because I'm using all available six pins for PWM (3,5,6,9,10,11)

The Code with only BLUE LED on Pin 11 
```
#include <IRremote.h> 
int RECV_PIN = 7; // IR SENSOR PIN
IRrecv irrecv(RECV_PIN);
decode_results results;

int BLUE1 = 11; // PIN FOR BLUE LED ON STRIP 1 
int RED1 = 10; // PIN FOR RED LED ON STRIP 1 
int GREEN1 = 9; // PIN FOR GREEN LED ON STRIP 1 
int BLUE2 = 6; // PIN FOR BLUE LED ON STRIP 2 
int RED2 = 5; // PIN FOR RED LED ON STRIP 2 
int GREEN2 = 3; // PIN FOR GREEN LED ON STRIP 2 

int blue1_brightness ;



void setup() {
 Serial.begin(9600);
 irrecv.enableIRIn();
 
pinMode(BLUE1,OUTPUT);
pinMode(RED1,OUTPUT);
pinMode(GREEN1,OUTPUT);
pinMode(BLUE2,OUTPUT);
pinMode(RED2,OUTPUT);
pinMode(GREEN2,OUTPUT);


}

void loop() {
   blue1_brightness = constrain(blue1_brightness, 0, 255); 
   analogWrite( BLUE1, blue1_brightness); 


 if (irrecv.decode(&results)) {
 Serial.println(results.value, HEX);

 //////  BLUE1 Volume Control //////
 if(results.value == 0xFF6897){
  blue1_brightness = blue1_brightness + 10;
 }
  if(results.value == 0xFF48B7){
  blue1_brightness = blue1_brightness - 10;
 }
 ////////////////////////////////

 irrecv.resume();
 }
}
```

**Comment by ArminJo** [comment]
Did you read the [FAQ](https://github.com/Arduino-IRremote/Arduino-IRremote#faq)?
But you can try to use the MinimalReceiver example, it requires no timer!
