### ISSUE TITLE
Teensy Compile error, "no match for 'operator+='"

### ISSUE THREAD

**Issue by cbradburne** [Arduino-IRremote/Arduino-IRremote#768]
### Board
* [x] Teensy board

### IDE
* [x] Arduino IDE

### Protocol
* [x] Sony

Here's the issue I'm having compiling IRSendDemo for Teensy 3.1/3.2,

```
"Arduino/libraries/IRremote/src/irPronto.cpp:266:10: error: no match for 'operator+=' (operand types are 'size_t {aka unsigned int}' and 'String')
     size += aString->concat(' ');"
```

**Comment by ArminJo** [comment]
Sorry but there is no further support possible, see: https://forum.pjrc.com/threads/65912-Enable-Continuous-Integration-with-arduino-cli-for-3-party-libraries 😞 
If you find a fix we can include it 😀
