### ISSUE TITLE
IF signal is not present, do something else

### ISSUE THREAD

**Issue by MTRobin** [Arduino-IRremote/Arduino-IRremote#769]
### Board
* [X] Arduino ATmega328* board (UNO, Nano)
* [ ] Arduino ATmega2560 board (Mega)
* [ ] Arduino ATmega32U4 board (Leonardo)
* [ ] ATtiny85 board (ATTinyCore by Spence Conde)
* [ ] Digispark board
* [ ] Arduino SAM board (Due)
* [ ] Arduino SAMD board (Zero, MKR*)
* [ ] ESP32 board - first check https://github.com/crankyoldgit/IRremoteESP8266
* [ ] Teensy board
* [ ] Other - please specify

### IDE
* [X] Arduino IDE
* [ ] Arduino Web Editor
* [ ] Arduino Pro IDE
* [ ] Sloeber IDE
* [ ] PlatformIO IDE
* [ ] Other - please specify

### Protocol
* [ ] Unknown
* [ ] BoseWave
* [ ] Denon
* [ ] Dish
* [ ] JVC
* [ ] Lego
* [X] LG
* [ ] NEC
* [ ] Panasonic
* [ ] RC5, RC6
* [ ] Samsung
* [ ] Sanyo
* [ ] Sharp
* [ ] Sony
* [ ] Whynter
* [ ] Other - please specify

### Code Block:
`#include <IRremote.h>

int IR_RECEIVE_PIN = 2;
int redPin = 5;
int greenPin = 9;
int bluePin = 6;
unsigned long color = 0x000000;

void setup() {
    Serial.begin(115200);
    IrReceiver.begin(IR_RECEIVE_PIN, ENABLE_LED_FEEDBACK); // Start the receiver, enable feedback LED, take LED feedback pin from the internal boards definition
    
    pinMode(redPin, OUTPUT);
    pinMode(greenPin, OUTPUT);
    pinMode(bluePin, OUTPUT);
}

void loop() {
    if (IrReceiver.decode() == true) {
      IrReceiver.printIRResultShort(&Serial);
      color = IrReceiver.decodedIRData.decodedRawData;
    }
    else {
      color = 0x000000;
    }
      analogWrite(redPin, color >> 16);
      analogWrite(greenPin, color >> 8 & 0xFF);
      analogWrite(bluePin, color & 0xFF);
      IrReceiver.resume();
}`

**checklist:**
- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] The latest [repo version](https://github.com/Arduino-IRremote/Arduino-IRremote/archive/master.zip) is used
- [X] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here
- [X] The title of the issue is helpful and relevant 

I am trying to create a conditional statement where if the signal is available try to decode it. If it is not do something else. Can you please give an example on how to do this?

The code I posted above doesn't resume the IrReceiver properly, and when I put the line `IrReceiver.resume();` within the first IF statement, it sees the signal, but my LED doesn't work properly.

Thank you,
Maxwell

**Comment by ArminJo** [comment]
This is NOT an issue.
