### ISSUE TITLE
The decode(&results) function stopped working 

### ISSUE THREAD

**Issue by chovanj** [Arduino-IRremote/Arduino-IRremote#771]
### Board
Tested on Arduino ATmega328* board UNO

### IDE
I use Arduino IDE 1.8.13

### Protocol
Tested on NEC and Samsung protocols.

It works for version 2.8.0, but doesn't for the latest versions.

#include <IRremote.h> 
...
if (irrecv.decode(&results))
...
results.value always return 0
...
but when I use if (irrecv.decode())
...
irrecv.results.value returns a correct value.
...

It looks that the decode(&results) function is broken in the 2.8.1 version - I see that version in the Manage Libraries window in Arduino IDE.

Anyway the library is perfect, I like it!
You're doing great job!

**Comment by ArminJo** [comment]
Thanks a lot for reporting! 👍 
I will insert a print statement to make things clearer.
