### ISSUE TITLE
Decoding Sony codes on Arduino Nano

### ISSUE THREAD

**Issue by schb9** [Arduino-IRremote/Arduino-IRremote#778]
If you have handling problems or questions, consider to open a discussion https://github.com/Arduino-IRremote/Arduino-IRremote/discussions instead of an issue.

### Board
* [x ] Arduino ATmega328* board (UNO, Nano)
Arduino Nano

### IDE
* [x ] Arduino IDE

### Protocol
* [x] Sony

* [ ] Other - please specify : also checked other remote controls : none decoded

your standard sample : IRreceiveDemo.cpp : IR_RECEIVE_PIN == 3

### Current behavior : pushing on/off button on Sony TV remote control
Using library version 3.0.0
Enabling IRin
Ready to receive IR signals at pin 3
Protocol=UNKNOWN 8 bits received
rawData[16]:
     -3276750
     + 200,-1300     + 200,-1400     + 150,-1450     + 150,-1400
     + 150,-1400     + 200,-1400     + 150,-1450     + 150

Protocol=UNKNOWN 8 bits received
rawData[16]:
     -14850
     + 200,-1400     + 150,-1400     + 150,-1450     + 150,-1400
     + 150,-3000     + 200,-3000     + 150,-3000     + 150

Protocol=UNKNOWN 10 bits received
rawData[20]:
     -17350
     + 250,-1350     + 150,-1450     + 100,-1450     + 150,-1450
     + 150,-1400     + 100,-1500     + 150,-3050     + 150,-2950
     + 150,-1450     +  50

Protocol=UNKNOWN 7 bits received
rawData[14]:
     -21700
     + 150,-1450     + 150,-1400     + 150,-1450     + 100,-3050
     + 150,-3000     + 200,-1350     + 200

### Expected behavior
protocol and code should be recognized

### Error output
see above

### Additional context

**checklist:**
- [x] I have **read** the README.md file thoroughly.
- [x] I have searched existing issues to see if there is anything I have missed.
- [x] The latest [repo version](https://github.com/Arduino-IRremote/Arduino-IRremote/archive/master.zip) is used.
- [x] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here.
- [x] The title of the issue is helpful and relevant.
- [x] I checked, if at least one of the examples was working.

** We will start to close issues that do not follow these guidelines as it doesn't help the contributors who spend time trying to solve issues if the community ignores guidelines!**

**Comment by ArminJo** [comment]
Duplicated to discussion 😀
