### ISSUE TITLE
Does IRremote library for arduino support Attiny13a? Is it possible to copy code from Arduino nano/uno to Attiny13a?

### ISSUE THREAD

**Issue by oishoweb** [Arduino-IRremote/Arduino-IRremote#796]
Does IRremote library for arduino support Attiny13a? Is it possible to copy code from Arduino nano/uno to Attiny13a?

### Board
* [ ] Arduino ATmega328* board (UNO, Nano)
* [ ] ATtiny13a

### IDE
* [ ] Arduino IDE

### Protocol
* [ ] NEC

**Comment by ArminJo** [comment]
All you can try is to port the [MinimalReceiver code](https://github.com/Arduino-IRremote/Arduino-IRremote/tree/master/examples/MinimalReceiver) to the attiny13.
Good luck.
