### ISSUE TITLE
ENABLE_LED_FEEDBACK / DISABLE_LED_FEEDBACK documentation

### ISSUE THREAD

**Issue by TheOldBrick** [Arduino-IRremote/Arduino-IRremote#822]
If you have handling problems or questions, consider to open a discussion https://github.com/ukw100/IRMP/discussions instead of an issue.

### Board
* [X] Arduino ATmega328* board (UNO, Nano)

### IDE
* [X] Arduino IDE

### Version
* [X] Other - please specify: 3.0.3 the latest version offered by the Arduino IDE Library Manager

### Pin(s) used for IR-receive, if not default: 11

**checklist:**
- [X] I have **read** the README.md file thoroughly.
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here.
- [X] The title of the issue is helpful and relevant.
- [X] I checked, if at least one of the examples was working.

### The Problem

Please enhance the README.md to clearly explain:
* ENABLE_LED_FEEDBACK on IrReceiver.begin
* DISABLE_LED_FEEDBACK on IrReceiver.begin
* What is the default when this argument is not specified?
* Which feedback LED?  A photo would be especially appropriate.  (I am using 1838T Infrared Receiver)

* In your "Issues" form, the address https://github.com/ukw100/IRMP/discussions returns a 404 error.

**Comment by ArminJo** [comment]
Thanks for reporting.
The Doxygen documentation is now avaliable at https://arduino-irremote.github.io/Arduino-IRremote/
