### ISSUE TITLE
Wrong RC5

### ISSUE THREAD

**Issue by MarianoDesivo** [Arduino-IRremote/Arduino-IRremote#826]
I measured RC5 signal with Proteus, simulating an Arduino UNO with IRRemote.h sending RC5

![image](https://user-images.githubusercontent.com/79780807/111925493-d5f8c300-8a87-11eb-994e-ea9c32d27fa4.png)
That is the smallest signal, a "0" to be read by the RC5 receviver

But the smallest signal is a 36kHz burst with 25%-33% of duty cycle. See explanation:
![image](https://user-images.githubusercontent.com/79780807/111925910-67b50000-8a89-11eb-851a-f0050464624d.png)
 
I test your library with my DVD Phillips and it kind of work, but not as good as It works with a well done signal (I made using atmega328). For example I can NOT turn on my DVD with your library

Give me some hints to fix that so I can make a Pull request. What file I have to look at to add the 36kHz burst?

I used last version (3.0.3)

**Comment by ArminJo** [comment]
Here is a live screenshot of a 328 RC5 PWM Signal with a duty cycle of 32%.
![IR_PWM_Send_only](https://github.com/Arduino-IRremote/Arduino-IRremote/blob/master/pictures/IR_PWM_by_software_detail.png)

> I test your library with my DVD Phillips and it kind of work, but not as good as It works with a well done signal

May I ask how you create this well done signal?

**Comment by MarianoDesivo** [comment]
> Here is a live screenshot of a 328 RC5 PWM Signal

So why I can't see that on Proteus? I can see it in the signal I made

> May I ask how you create this well done signal?

I will be uploading the library, I can tell you when it's done if you want. Basically I made it using Atmega Fast PWM (at 36kHz, 28%), and an interruption with counters
