### ISSUE TITLE
for what reason?

### ISSUE THREAD

**Issue by upl1nk-v01d** [Arduino-IRremote/Arduino-IRremote#842]
I'm still struggling to find a way to receive and send IR codes with ATtiny85.
With new IR library I can receive IR codes, but not send. However, with old library - only send.
Half a year ago with good old library my Arduino and ATtiny code and same connection setup worked without any problem.
???What a hell did you do guys??? :(

**Comment by ArminJo** [comment]
Please do me a favor and check the [UnitTest example](https://github.com/Arduino-IRremote/Arduino-IRremote/blob/master/examples/UnitTest/UnitTest.ino)
