### ISSUE TITLE
Trouble reading IR values

### ISSUE THREAD

**Issue by jdsantelicesl** [Arduino-IRremote/Arduino-IRremote#861]
If you have handling problems or questions, consider to open a discussion https://github.com/Arduino-IRremote/Arduino-IRremote/discussions instead of an issue.

### Board
* [ ] Arduino ATmega328* board (UNO, Nano)

### IDE
* [ ] Arduino IDE

### Protocol
* [ ] Unknown

### Version
* [ ] Yes I use the [latest repo version](https://github.com/Arduino-IRremote/Arduino-IRremote/archive/master.zip) and

### Pin(s) used for IR-receive, if not default: default pins (send pin3, recieve pin 11).

#include <IRremote.h>

IRsend irsend;

int RECV_PIN = 11;

IRrecv irrecv(RECV_PIN);

decode_results results;

void setup()
{
  Serial.begin(9600);
  Serial.println("Enabling IRin");
  irrecv.enableIRIn(); // Start the receiver
  Serial.println("Enabled IRin");
}

void loop() {
  for (int i = 0; i < 3; i++) {
    irsend.sendSony(0xa90, 12);
    delay(40);
  }
  delay(5000);
  
  if (irrecv.decode(&results)) {
    Serial.println(results.value, HEX);
    irrecv.resume(); // Receive the next value
  }
  delay(100);
}

.....

```


### Current behavior

avrdude: loadaddr(): (b) protocol error, expect=0x14, resp=0x00

avrdude: stk500_paged_load(): (a) protocol error, expect=0x14, resp=0x00
avrdude: stk500_cmd(): programmer is out of sync
avr_read(): error reading address 0x0000
    read operation not supported for memory "flash"
avrdude: failed to read all of flash memory, rc=-2
avrdude: stk500_disable(): protocol error, expect=0x14, resp=0x00
avrdude: ser_close(): can't reset attributes for device: Invalid argument
the selected serial port avrdude: ser_close(): can't reset attributes for device: Invalid argument
 does not exist or your board is not connected


Description: Every time I try to upload to Arduino Uno, I get an error message in the terminal. Sometimes it uploads either way and I get the "enabling" and "enabled" messages in the Serial Monitor, but I am unable to read the IR code. 

### Expected behavior

Serial Monitor should display the values read with the IR reciever. 

### Additional context

Reciever Module is flashing, meaning that it is not a hardware problem. It is my first time using the library.

Hope I find the error, Thank You!

**Comment by ArminJo** [comment]
Sorry, but this is no issue of the library!!!
