### ISSUE TITLE
Use arduino uno as an air conditioner remote control 

### ISSUE THREAD

**Issue by Zeller-zf** [Arduino-IRremote/Arduino-IRremote#874]
### Board
* [ ] Arduino (UNO)

### IDE
* [ ] Arduino IDE

### Protocol
Protocol=PULSE_DISTANCE

###Problem
I ran the ReceiveDump.cpp in Arduino (UNO).
And I received

Protocol=PULSE_DISTANCE Address=0x0 Command=0x0 Raw-Data=0xF40B02FD 98 bits LSB first

Raw result in internal ticks (50 us) - with leading gap
rawData[200]: 
     -65535
     +  86,-  88     +   9,-  34     +  10,-  12     +   9,-  34
     +   9,-  34     +   9,-  12     +   9,-  12     +  10,-  34
     +   9,-  12     +   9,-  12     +   9,-  34     +   9,-  13
     +   9,-  12     +   9,-  34     +   9,-  34     +   9,-  12
     +   9,-  34     +   9,-  35     +   9,-  12     +   9,-  34
     +   9,-  34     +   9,-  34     +   9,-  34     +   9,-  34
     +   9,-  34     +   9,-  13     +   9,-  34     +   9,-  12
     +   9,-  12     +   9,-  13     +   9,-  12     +   9,-  12
     +   9,-  13     +   9,-  34     +   9,-  34     +   9,-  12
     +   9,-  34     +   9,-  13     +   9,-  12     +   9,-  12
     +   9,-  12     +   9,-  13     +   9,-  12     +   9,-  34
     +   9,-  12     +   9,-  34     +  10,-  34     +   9,-  34
     +   9,-  34     +   9,- 105     +  85,-  89     +   9,-  34
     +   9,-  12     +   9,-  35     +   9,-  34     +   9,-  12
     +   9,-  12     +   9,-  34     +   9,-  13     +   9,-  12
     +   9,-  34     +   9,-  12     +   9,-  13     +   9,-  34
     +   9,-  34     +   9,-  12     +   9,-  34     +   9,-  34
     +   9,-  13     +   9,-  34     +   9,-  34     +   9,-  34
     +   9,-  34     +   9,-  34     +   9,-  34     +   9,-  13
     +   9,-  34     +   9,-  12     +   9,-  12     +   9,-  13
     +   9,-  12     +   9,-  12     +   9,-  12     +   9,-  35
     +   9,-  34     +   9,-  12     +   9,-  34     +   9,-  12
     +  10,-  12     +   9,-  12     +   9,-  12     +   9,-  13
     +   9,-  12     +   9,-  34     +   9,-  12     +   9,-  34
     +   9,-  34     +   9,-  35     +   9,-  34     +   9
Raw result in microseconds - with leading gap
rawData[200]: 
     -3276750
     +4300,-4400     + 450,-1700     + 500,- 600     + 450,-1700
     + 450,-1700     + 450,- 600     + 450,- 600     + 500,-1700
     + 450,- 600     + 450,- 600     + 450,-1700     + 450,- 650
     + 450,- 600     + 450,-1700     + 450,-1700     + 450,- 600
     + 450,-1700     + 450,-1750     + 450,- 600     + 450,-1700
     + 450,-1700     + 450,-1700     + 450,-1700     + 450,-1700
     + 450,-1700     + 450,- 650     + 450,-1700     + 450,- 600
     + 450,- 600     + 450,- 650     + 450,- 600     + 450,- 600
     + 450,- 650     + 450,-1700     + 450,-1700     + 450,- 600
     + 450,-1700     + 450,- 650     + 450,- 600     + 450,- 600
     + 450,- 600     + 450,- 650     + 450,- 600     + 450,-1700
     + 450,- 600     + 450,-1700     + 500,-1700     + 450,-1700
     + 450,-1700     + 450,-5250     +4250,-4450     + 450,-1700
     + 450,- 600     + 450,-1750     + 450,-1700     + 450,- 600
     + 450,- 600     + 450,-1700     + 450,- 650     + 450,- 600
     + 450,-1700     + 450,- 600     + 450,- 650     + 450,-1700
     + 450,-1700     + 450,- 600     + 450,-1700     + 450,-1700
     + 450,- 650     + 450,-1700     + 450,-1700     + 450,-1700
     + 450,-1700     + 450,-1700     + 450,-1700     + 450,- 650
     + 450,-1700     + 450,- 600     + 450,- 600     + 450,- 650
     + 450,- 600     + 450,- 600     + 450,- 600     + 450,-1750
     + 450,-1700     + 450,- 600     + 450,-1700     + 450,- 600
     + 500,- 600     + 450,- 600     + 450,- 600     + 450,- 650
     + 450,- 600     + 450,-1700     + 450,- 600     + 450,-1700
     + 450,-1700     + 450,-1750     + 450,-1700     + 450

Result as internal ticks (50 us) array - compensated with MARK_EXCESS_MICROS=20
uint8_t rawTicks[199] = {86,88, 9,34, 10,12, 9,34, 9,34, 9,12, 9,12, 10,34, 9,12, 9,12, 9,34, 9,13, 9,12, 9,34, 9,34, 9,12, 9,34, 9,35, 9,12, 9,34, 9,34, 9,34, 9,34, 9,34, 9,34, 9,13, 9,34, 9,12, 9,12, 9,13, 9,12, 9,12, 9,13, 9,34, 9,34, 9,12, 9,34, 9,13, 9,12, 9,12, 9,12, 9,13, 9,12, 9,34, 9,12, 9,34, 10,34, 9,34, 9,34, 9,105, 85,89, 9,34, 9,12, 9,35, 9,34, 9,12, 9,12, 9,34, 9,13, 9,12, 9,34, 9,12, 9,13, 9,34, 9,34, 9,12, 9,34, 9,34, 9,13, 9,34, 9,34, 9,34, 9,34, 9,34, 9,34, 9,13, 9,34, 9,12, 9,12, 9,13, 9,12, 9,12, 9,12, 9,35, 9,34, 9,12, 9,34, 9,12, 10,12, 9,12, 9,12, 9,13, 9,12, 9,34, 9,12, 9,34, 9,34, 9,35, 9,34, 9};  // Protocol=PULSE_DISTANCE Address=0x0 Command=0x0 Raw-Data=0xF40B02FD 98 bits LSB first

Result as microseconds array - compensated with MARK_EXCESS_MICROS=20
uint16_t rawData[199] = {4280,4420, 430,1720, 480,620, 430,1720, 430,1720, 430,620, 430,620, 480,1720, 430,620, 430,620, 430,1720, 430,670, 430,620, 430,1720, 430,1720, 430,620, 430,1720, 430,1770, 430,620, 430,1720, 430,1720, 430,1720, 430,1720, 430,1720, 430,1720, 430,670, 430,1720, 430,620, 430,620, 430,670, 430,620, 430,620, 430,670, 430,1720, 430,1720, 430,620, 430,1720, 430,670, 430,620, 430,620, 430,620, 430,670, 430,620, 430,1720, 430,620, 430,1720, 480,1720, 430,1720, 430,1720, 430,5270, 4230,4470, 430,1720, 430,620, 430,1770, 430,1720, 430,620, 430,620, 430,1720, 430,670, 430,620, 430,1720, 430,620, 430,670, 430,1720, 430,1720, 430,620, 430,1720, 430,1720, 430,670, 430,1720, 430,1720, 430,1720, 430,1720, 430,1720, 430,1720, 430,670, 430,1720, 430,620, 430,620, 430,670, 430,620, 430,620, 430,620, 430,1770, 430,1720, 430,620, 430,1720, 430,620, 480,620, 430,620, 430,620, 430,670, 430,620, 430,1720, 430,620, 430,1720, 430,1720, 430,1770, 430,1720, 430};  // Protocol=PULSE_DISTANCE Address=0x0 Command=0x0 Raw-Data=0xF40B02FD 98 bits LSB first

uint16_t address = 0x0;
uint16_t command = 0x0;
uint32_t data = 0xF40B02FD;

Pronto Hex as string
char ProntoData[] = "0000 006D 0064 0000 00A6 00A8 0012 0041 0014 0016 0012 0041 0012 0041 0012 0016 0012 0016 0014 0041 0012 0016 0012 0016 0012 0041 0012 0018 0012 0016 0012 0041 0012 0041 0012 0016 0012 0041 0012 0043 0012 0016 0012 0041 0012 0041 0012 0041 0012 0041 0012 0041 0012 0041 0012 0018 0012 0041 0012 0016 0012 0016 0012 0018 0012 0016 0012 0016 0012 0018 0012 0041 0012 0041 0012 0016 0012 0041 0012 0018 0012 0016 0012 0016 0012 0016 0012 0018 0012 0016 0012 0041 0012 0016 0012 0041 0014 0041 0012 0041 0012 0041 0012 00C9 00A4 00AA 0012 0041 0012 0016 0012 0043 0012 0041 0012 0016 0012 0016 0012 0041 0012 0018 0012 0016 0012 0041 0012 0016 0012 0018 0012 0041 0012 0041 0012 0016 0012 0041 0012 0041 0012 0018 0012 0041 0012 0041 0012 0041 0012 0041 0012 0041 0012 0041 0012 0018 0012 0041 0012 0016 0012 0016 0012 0018 0012 0016 0012 0016 0012 0016 0012 0043 0012 0041 0012 0016 0012 0041 0012 0016 0014 0016 0012 0016 0012 0016 0012 0018 0012 0016 0012 0041 0012 0016 0012 0041 0012 0041 0012 0043 0012 0041 0012 06C3 "

Pronto HEX contains: 0000 006D 0064 0000 00A6 00A8 0012 0041 0014 0016 0012 0041 0012 0041 0012 0016 0012 0016 0014 0041 0012 0016 0012 0016 0012 0041 0012 0018 0012 0016 0012 0041 0012 0041 0012 0016 0012 0041 0012 0043 0012 0016 0012 0041 0012 0041 0012 0041 0012 0041 0012 0041 0012 0041 0012 0018 0012 0041 0012 0016 0012 0016 0012 0018 0012 0016 0012 0016 0012 0018 0012 0041 0012 0041 0012 0016 0012 0041 0012 0018 0012 0016 0012 0016 0012 0016 0012 0018 0012 0016 0012 0041 0012 0016 0012 0041 0014 0041 0012 0041 0012 0041 0012 00C9 00A4 00AA 0012 0041 0012 0016 0012 0043 0012 0041 0012 0016 0012 0016 0012 0041 0012 0018 0012 0016 0012 0041 0012 0016 0012 0018 0012 0041 0012 0041 0012 0016 0012 0041 0012 0041 0012 0018 0012 0041 0012 0041 0012 0041 0012 0041 0012 0041 0012 0041 0012 0018 0012 0041 0012 0016 0012 0016 0012 0018 0012 0016 0012 0016 0012 0016 0012 0043 0012 0041 0012 0016 0012 0041 0012 0016 0014 0016 0012 0016 0012 0016 0012 0018 0012 0016 0012 0041 0012 0016 0012 0041 0012 codes

How can I control my air conditioner??

**Comment by ArminJo** [comment]
Please read the readme carefully! This is NO issue!
