### ISSUE TITLE
How did you create the IR code screenshots in the readme guide near the bottom

### ISSUE THREAD

**Issue by davidlittle18** [Arduino-IRremote/Arduino-IRremote#878]
Hi,

I wondered if you could explain what program you used to make these pictures as they are very clear and helpful.

<img width="871" alt="Screenshot 2021-08-07 at 11 41 16" src="https://user-images.githubusercontent.com/76871862/128597465-86a659ec-4f4f-4240-8a1e-501c0d72d113.png">

Thanks,

**Comment by AnalysIR** [comment]
You should be able to get similar images with Logic Analyzer software (Sigrok/Pulseview, Saleae etc). However, there will be limited support except for the most popular IR protocols.

_PS: you should probably make this a discussion (not an issue)_
