### ISSUE TITLE
error: 'class IRrecv' has no member named 'blink13'

### ISSUE THREAD

**Issue by ArminJo** [Arduino-IRremote/Arduino-IRremote#889]
### Discussed in https://github.com/Arduino-IRremote/Arduino-IRremote/discussions/888

<div type='discussions-op-text'>

<sup>Originally posted by **greenonline** September  5, 2021</sup>
A number of the examples on the web, Arduino forum and YouTube tutorials (i.e. [Robotics Training LESSON 11: Controlling the Elegoo Smart Car With IR Remote](https://www.youtube.com/watch?v=RG95UxBSN0M&list=PLGs0VKk2DiYxkoe2XNxDvVHqL5XG4dMWi&index=11) at [**16:40**](https://www.youtube.com/watch?v=RG95UxBSN0M&list=PLGs0VKk2DiYxkoe2XNxDvVHqL5XG4dMWi&index=11&t=1000)) use the line

```
IR.blink13(true);
```

However, I always seem to get the error

```
/Users/macbook/Documents/Arduino/IRremote_1/IRremote_1.ino: In function 'void setup()':
IRremote_1:34:10: error: 'class IRrecv' has no member named 'blink13'
   irrecv.blink13(true); // blink LED on P13 when IR signal is present
          ^~~~~~~
```

I have searched extensively, and while there are many mentions of the code changes required to sketches for v3 (i.e. the deprecated code, etc.), no one seems to be talking about `blink13()` disappearing... so I am starting to wonder whether:

a) I have a dodgy installation, and it hasn't *actually* been removed, or; 
b) There is some really obvious code typo that I just can't see.

It isn't even mentioned in the README.md under the [new version features](https://github.com/Arduino-IRremote/Arduino-IRremote#features-of-the-3x-version) nor [conversion from 2.x to 3.x](https://github.com/Arduino-IRremote/Arduino-IRremote#converting-your-2x-program-to-the-3x-version).

Has it been removed from version 3?

If it has been removed, why was it removed and is there an alternative function?</div>

**Comment by greenonline** [comment]
OK, I've just tried the latest and it successfully compiles, with the following deprecation warning (which I presume is correct):

```

/Users/macbook/Documents/Arduino/IRremote_Test/IRremote_Test.ino: In function 'void setup()':
/Users/macbook/Documents/Arduino/IRremote_Test/IRremote_Test.ino:28:20: warning: 'void IRrecv::blink13(bool)' is deprecated: Please use setLEDFeedback() or enableLEDFeedback() / disableLEDFeedback(). [-Wdeprecated-declarations]
     IR.blink13(true);
```

Good job!
