### ISSUE TITLE
Serial. Monitor output error.

### ISSUE THREAD

**Issue by Riz1ahmed** [Arduino-IRremote/Arduino-IRremote#901]
I am trying to out remote key value using Serial monitor. But it getting yjis error

`PULSE_DISTANCE: HeaderMarkMicros=8900 HeaderSpaceMicros=4450 MarkMicros=550 OneSpaceMicros=1700 ZeroSpaceMicros=600
 0x43D8613C 0x3BC3BC
`

**Comment by ArminJo** [comment]
If you want to help us improving the library, please replace the old ir_DistanceProtocol.cpp with the new one from the repository and test again and post the output.
