### ISSUE TITLE
[Bug]: ESP32 Devkit 1: "Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled" on SendDemo

### ISSUE THREAD

**Issue by adrian-dobre** [Arduino-IRremote/Arduino-IRremote#927]
### The type of board you are using.

ESP32 board - first check https://github.com/crankyoldgit/IRremoteESP8266

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

NEC

### Pin(s) used for IR-receive, if not default.

Arduino pin number: 

### Example(s) you have checked while hunting the bug.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] MinimalReceiver
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [X] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [ ] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] MinimalReceiver
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [X] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [ ] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

1. Fire up SendDemo example using version 3.5.0

### What happens?

ESP32 Crash:
```
START C:\Users\adrian\Documents\Arduino\libraries\IRremote\examples\SendDemo\SendDemo.ino from Dec 15 2021
Using library version 3.5.0
Ready to send IR signals at pin 4

address=0x102 command=0x34 repeats=0


Send NEC with 8 bit address
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400813cb  PS      : 0x00060530  A0      : 0x800d0f16  A1      : 0x3ffb1e40  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x3ffb8218  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0xff000000  A8      : 0x80085e98  A9      : 0x3ffb1e20  
A10     : 0x00000000  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x00000001  
A14     : 0x00060520  A15     : 0x00000000  SAR     : 0x0000001e  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

ELF file SHA256: 0000000000000000

Backtrace: 0x400813cb:0x3ffb1e40 0x400d0f13:0x3ffb1e60 0x400d13ba:0x3ffb1e80 0x400d1442:0x3ffb1eb0 0x400d1b4a:0x3ffb1ee0 0x400d2cdd:0x3ffb1fb0 0x40086429:0x3ffb1fd0

```

**It doesn't crash on 3.4.0**

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Thanks a lot for reporting! 🥇
