### ISSUE TITLE
[Bug]: stiil get comilation warning

### ISSUE THREAD

**Issue by Skywalkerf34** [Arduino-IRremote/Arduino-IRremote#962]
### The type of board you are using.

ESP32 board - first check https://github.com/crankyoldgit/IRremoteESP8266

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

NEC

### Pin(s) used for IR-receive, if not default.

Arduino pin number: 7

### Example(s) you have checked while hunting the bug.

- [X] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] MinimalReceiver
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below
- [X] I checked, if at least one of the examples was working.

### Example(s) to reproduce the issue.

- [X] SimpleReceiver
- [ ] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] MinimalReceiver
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [ ] Other - please specify below

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [X] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

  IrReceiver.begin(IR_RECEIVE_PIN,disableLEDFeedback);

### What happens?

Still got a compilation warning 

### The serial output which indicates the error happened.

```shell
In file included from d:\Users\FidL\Documents\Arduino\libraries\IRremote\src/IRFeedbackLED.hpp:34,
                 from d:\Users\FidL\Documents\Arduino\libraries\IRremote\src/IRremote.hpp:218,
                 from d:\Users\FidL\Documents\Arduino\libraries\IRremote\src/IRremote.h:10,
                 from d:\Users\FidL\Documents\Arduino\ESP32_C3_miniVeg\ESP32_C3_miniVeg.ino:90:
d:\Users\FidL\Documents\Arduino\libraries\IRremote\src/private/IRFeedbackLEDDefs.h:83:2: warning: #warning No definition for LED_BUILTIN for default feedback LED found. Check private/IRFeedbackLEDDefs.h. [-Wcpp]
 #warning No definition for LED_BUILTIN for default feedback LED found. Check private/IRFeedbackLEDDefs.h.
```

### What were you expecting to happen?

as I was expecting disabling LED, no more warning

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Thanks for reporting. 👍  There were some inconsistencies in the code 😞 
I changed the message to 
`#warning INFO: No definition for LED_BUILTIN found -> default LED feedback is disabled.`
I hope it is more understandable now.
