### ISSUE TITLE
[Bug]: NEC Code: 0x2 is being received as 0x4 and 0xB is received as 0xD.

### ISSUE THREAD

**Issue by Ativerc** [Arduino-IRremote/Arduino-IRremote#991]
### The type of board you are using.

Arduino ATmega328* board (UNO, Nano, etc.)

### What IDE are you using?

Arduino IDE

### What IR protocol are you using?

NEC

### Pin(s) used for IR-receive, if not default.

Arduino pin number: 2

### Example(s) you have checked while hunting the bug.

- [ ] SimpleReceiver
- [X] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] MinimalReceiver
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [X] Other - please specify below
- [X] I checked, if at least one of the examples was working.
- [X] ReceiveDump
- [X] IRremote v2.5's IRrecvDumpV2

### Example(s) to reproduce the issue.

- [ ] SimpleReceiver
- [X] ReceiveDemo
- [ ] SendRawDemo
- [ ] ReceiverTimingAnalysis
- [ ] MinimalReceiver
- [ ] ReceiveAndSend
- [ ] SimpleSender
- [ ] SendDemo
- [ ] SendLGAirConditionerDemo
- [ ] UnitTest
- [X] Other - please specify below
- [X] ReceiveDump
- [X] IRremote v2.5's IRrecvDumpV2

### The library version you are working with.

- [X] I use the [latest Arduino library version](../releases) and verified this!
- [ ] I use the latest repo version ([download link](../archive/master.zip)) and verified this!

### What are the steps to reproduce this issue?

Use Arduino UNO with TSOP38238 and ArduinoIRRemote library.
Get a phone with an IR blaster and an App which can show you the NEC command being sent. I am using IR Code Finder NEC https://play.google.com/store/apps/details?id=ru.wasiliysoft.ircodefindernec 
Point the Phone's IR blaster to the device and send a command which the device responds to, and now check the same command with ReceiveDump or ReceiveDemo.

### What happens?

You will see that the IR command sent by the remote when received by the ReceiveDump or ReceiveDemo will have
1. its `0x2` switched to `0x4` (and vice-versa)
2. its 0xB switched by `0xD` (and vice-versa)

For the code sent by the app, `0x00FB6996`<sub>MSB</sub> is received as `0x6996DF00`<sub>LSB</sub> by ReceiveDump and ReceiveDemo.

### The serial output which indicates the error happened.

```shell
This is a semantic error.
```

### What were you expecting to happen?

The code sent by the device remote or the IR App should be the same received/decoded by the IRRemote's examples. It's not happening here for some reason.

### Additional context.

To confirm that it was not some hardware error, I tried other codes:
1. `0x4BB622DD`<sub>MSB</sub> is received as `0xBB446DD2`<sub>LSB</sub> (`0x2DD644BB`<sub>MSB</sub>)

## `0x00FB6996`<sub>MSB</sub>

To further confirm that this wasn't a mistake with the Android App, I installed v2.5 of IRRemote and here's the output for the same `0x00FB6996`<sub>MSB</sub> code from v2.5's `IRrecvDumpV2`:

`//Arduino Uno v3 + TSOP38238 + IRremote v2.5's IRrecvDumpV2 Output: `

```
Encoding  : NEC
Code      : 0xFB6996 (32 bits)
Timing[67]: 
     +9050, -4550     + 600, - 500     + 600, - 550     + 600, - 550
     + 600, - 550     + 600, - 500     + 600, - 550     + 600, - 550
     + 600, - 550     + 550, -1700     + 600, -1700     + 550, -1700
     + 600, -1650     + 600, -1700     + 550, - 600     + 550, -1700
     + 600, -1650     + 600, - 550     + 600, -1650     + 600, -1700
     + 600, - 550     + 600, -1650     + 600, - 550     + 600, - 550
     + 550, -1700     + 600, -1650     + 600, - 550     + 600, - 550
     + 550, -1700     + 600, - 550     + 550, -1700     + 600, -1650
     + 600, - 550     + 600
Pronto Hex: 0000 006D 0022 0000 015C 00AF 0017 0013 0017 0015 0017 0015 0017 0015 0017 0013 0017 0015 0017 0015 0017 0015 0015 0041 0017 0041 0015 0041 0017 003F 0017 0041 0015 0017 0015 0041 0017 003F 0017 0015 0017 003F 0017 0041 0017 0015 0017 003F 0017 0015 0017 0015 0015 0041 0017 003F 0017 0015 0017 0015 0015 0041 0017 0015 0015 0041 0017 003F 0017 0015 0017 0806 
unsigned int  rawData[67] = {9050,4550, 600,500, 600,550, 600,550, 600,550, 600,500, 600,550, 600,550, 600,550, 550,1700, 600,1700, 550,1700, 600,1650, 600,1700, 550,600, 550,1700, 600,1650, 600,550, 600,1650, 600,1700, 600,550, 600,1650, 600,550, 600,550, 550,1700, 600,1650, 600,550, 600,550, 550,1700, 600,550, 550,1700, 600,1650, 600,550, 600};  // NEC FB6996
unsigned int  data = 0xFB6996;
```

This is the exact code sent by my Android App and the device remote. The device responds to the above code as expected/nominally.

Compare that with v3.6.1's ReceiveDump's output for `0x00FB6996`<sub>MSB</sub>:

`//Arduino Uno v3 + TSOP38238 + IRremote v3.6.1 ReceiveDump Output:`
```
rotocol=NEC Address=0xDF00 Command=0x96 Raw-Data=0x6996DF00 32 bits LSB first

Raw result in internal ticks (50 us) - with leading gap
rawData[68]: 
     -47474
     + 182,-  91     +  12,-  11     +  11,-  11     +  12,-  11
     +  12,-  11     +  12,-  10     +  12,-  11     +  12,-  11
     +  12,-  10     +  12,-  34     +  12,-  33     +  12,-  34
     +  11,-  34     +  12,-  34     +  11,-  11     +  12,-  33
     +  12,-  34     +  12,-  11     +  12,-  33     +  12,-  34
     +  12,-  10     +  12,-  34     +  12,-  11     +  11,-  11
     +  12,-  34     +  11,-  34     +  12,-  11     +  11,-  12
     +  11,-  34     +  11,-  12     +  11,-  34     +  11,-  34
     +  12,-  11     +  12
Raw result in microseconds - with leading gap
rawData[68]: 
     -2373700
     +9100,-4550     + 600,- 550     + 550,- 550     + 600,- 550
     + 600,- 550     + 600,- 500     + 600,- 550     + 600,- 550
     + 600,- 500     + 600,-1700     + 600,-1650     + 600,-1700
     + 550,-1700     + 600,-1700     + 550,- 550     + 600,-1650
     + 600,-1700     + 600,- 550     + 600,-1650     + 600,-1700
     + 600,- 500     + 600,-1700     + 600,- 550     + 550,- 550
     + 600,-1700     + 550,-1700     + 600,- 550     + 550,- 600
     + 550,-1700     + 550,- 600     + 550,-1700     + 550,-1700
     + 600,- 550     + 600

Result as internal ticks (50 us) array - compensated with MARK_EXCESS_MICROS=20
uint8_t rawTicks[67] = {182,91, 12,11, 11,11, 12,11, 12,11, 12,10, 12,11, 12,11, 12,10, 12,34, 12,33, 12,34, 11,34, 12,34, 11,11, 12,33, 12,34, 12,11, 12,33, 12,34, 12,10, 12,34, 12,11, 11,11, 12,34, 11,34, 12,11, 11,12, 11,34, 11,12, 11,34, 11,34, 12,11, 12};  // Protocol=NEC Address=0xDF00 Command=0x96 Raw-Data=0x6996DF00 32 bits LSB first

Result as microseconds array - compensated with MARK_EXCESS_MICROS=20
uint16_t rawData[67] = {9080,4570, 580,570, 530,570, 580,570, 580,570, 580,520, 580,570, 580,570, 580,520, 580,1720, 580,1670, 580,1720, 530,1720, 580,1720, 530,570, 580,1670, 580,1720, 580,570, 580,1670, 580,1720, 580,520, 580,1720, 580,570, 530,570, 580,1720, 530,1720, 580,570, 530,620, 530,1720, 530,620, 530,1720, 530,1720, 580,570, 580};  // Protocol=NEC Address=0xDF00 Command=0x96 Raw-Data=0x6996DF00 32 bits LSB first

uint16_t address = 0xDF00;
uint16_t command = 0x96;
uint32_t data = 0x6996DF00;

Pronto Hex as string
char prontoData[] = "0000 006D 0022 0000 015F 00AE 0018 0014 0016 0014 0018 0014 0018 0014 0018 0012 0018 0014 0018 0014 0018 0012 0018 0041 0018 003F 0018 0041 0016 0041 0018 0041 0016 0014 0018 003F 0018 0041 0018 0014 0018 003F 0018 0041 0018 0012 0018 0041 0018 0014 0016 0014 0018 0041 0016 0041 0018 0014 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0018 0014 0018 06C3 ";
```

That code when sent by the App doesn't elicit any response by the device.

P.S: The title could be better. And I have tried to give you all the information in the format asked for.
PPS: The raw codedump's as per IRRemote v2.5's IRrecvDumpV2  for all commands of the device in question can be found here:  https://github.com/Ativerc/one-remote-group/blob/master/Resources/Data/raw_remote_data/Superfan_Remote_Codes.txt

### Final checklist for the bug report.

- [X] I have **read** the README.md file thoroughly
- [X] I have searched existing issues to see if there is anything I have missed.
- [X] I have browsed the examples for one, that matches my use case.
- [X] The title of the issue is helpful and relevant.

**Comment by ArminJo** [comment]
Ever read https://github.com/Arduino-IRremote/Arduino-IRremote#how-to-convert-old-msb-first-32-bit-ir-data-codes-to-new-lsb-first-32-bit-ir-data-codes ???
